version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-5.3
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.3"

  unit-tests:
    image: swift-nio:16.04-5.3

  integration-tests:
    image: swift-nio:16.04-5.3

  test:
    image: swift-nio:16.04-5.3
    environment:
      - MAX_ALLOCS_ALLOWED_1000_addHandlers=45050
      - MAX_ALLOCS_ALLOWED_1000_addHandlers_sync=38050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlercontext=9050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlername=9050
      - MAX_ALLOCS_ALLOWED_1000_addRemoveHandlers_handlertype=9050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet=21050
      - MAX_ALLOCS_ALLOWED_1000_autoReadGetAndSet_sync=0
      - MAX_ALLOCS_ALLOWED_1000_copying_bytebufferview_to_array=1050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers=9050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers_sync=35
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=30400
      - MAX_ALLOCS_ALLOWED_1000_tcpbootstraps=4050
      - MAX_ALLOCS_ALLOWED_1000_tcpconnections=156050
      - MAX_ALLOCS_ALLOWED_1000_udp_reqs=12050
      - MAX_ALLOCS_ALLOWED_1000_udpbootstraps=2050
      - MAX_ALLOCS_ALLOWED_1000_udpconnections=83050
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=406050
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2050
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=0
      - MAX_ALLOCS_ALLOWED_decode_1000_ws_frames=2050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer=3
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space=3
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer=3050
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space=3050
      - MAX_ALLOCS_ALLOWED_execute_hop_10000_tasks=0
      - MAX_ALLOCS_ALLOWED_future_erase_result=4050
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=60050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=700050
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=0
      - MAX_ALLOCS_ALLOWED_modifying_byte_buffer_view=2050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4350
      - MAX_ALLOCS_ALLOWED_read_10000_chunks_from_file=170050
      - MAX_ALLOCS_ALLOWED_schedule_10000_tasks=60100
      - MAX_ALLOCS_ALLOWED_schedule_and_run_10000_tasks=60050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=98
      - MAX_ALLOCS_ALLOWED_udp_1000_reqs_1_conn=12150
      - MAX_ALLOCS_ALLOWED_udp_1_reqs_1000_conn=166050
      - SANITIZER_ARG=--sanitize=thread

  performance-test:
    image: swift-nio:16.04-5.3

  shell:
    image: swift-nio:16.04-5.3

  echo:
    image: swift-nio:16.04-5.3

  http:
    image: swift-nio:16.04-5.3
